[package]
name = "ipfs-api"
version = "0.1.4"
authors = ["rmnoff <romanov.spb.alex@yandex.ru>"]

[dependencies]
curl = "*"
json = "*"
time = "*"
rustc-serialize = "*"
jsonify = { git = "https://github.com/rmnoff/jsonify" }
