[package]
name = "ipfs-api"
version = "0.1.4"
authors = ["Brandon Richardson <brandon.richardson4328@outlook.com>"]
[dependencies]
curl = "*"
json = "*"
time = "*"
rustc-serialize = "*"
jsonify = { git = "https://github.com/rmnoff/jsonify" }
